spring.application.name=MySpringBoot

# port number
server.port=8080

# 사용자 정의 환경 변수
myboot.age=${random.int(1,100)}
myboot.fullName=${myboot.name} Boot

# 현재 활성화된 Profile 값 설정 test|prod
spring.profiles.active=prod